// <auto-generated />
using System;
using AndonDashBroad.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AndonDashBroad.Migrations
{
    [DbContext(typeof(AndonDbContext))]
    partial class AndonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("SharedLib.Model.IncidentTicket", b =>
                {
                    b.Property<string>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AlarmTypeIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("FixNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaderConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LineNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Product")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TechCheckinAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TechFixedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicianName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkOrder")
                        .HasColumnType("TEXT");

                    b.HasKey("TicketId");

                    b.ToTable("IncidentTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
